### ISSUE TITLE
Chapter Idea

### ISSUE THREAD

**Issue by MChorfa** [dart4hipsters/dart4hipsters.github.com#4]
Modules and   dependencies of ressources like [require.js]

**Comment by eee-c** [comment]
I think this is already covered by the libraries chapter. Dart's built-in #library macro works very much like require.js -- only better :)

Do you have the book? Were you hoping for more than is already in there?

**Comment by MChorfa** [comment]
No not yet, i subscribed and i'm wiating for signe to shop it

**Comment by MChorfa** [comment]
It wold be interesting to cover the of REST or restful api.
